project_id = "nvnxptkgksuhfcpmungq"

[functions.generate-budget]
verify_jwt = false

[functions.vision-ai]
verify_jwt = true

[functions.image-processing]
verify_jwt = true

[functions.generate-ai]
verify_jwt = true

[functions.process-room-phase]
verify_jwt = true
