// PDF Export Service for HOUSPIRE
// Generate comprehensive project reports and presentations

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatIndianCurrency } from './budgetCalculatorService';

export interface ProjectExportData {
  projectName: string;
  clientName: string;
  city: string;
  date: string;
  rooms: Array<{
    roomName: string;
    roomType: string;
    area: number;
    originalImage?: string;
    cleanedImage?: string;
    renderImage?: string;
    style?: string;
    budget?: number;
    doors?: number;
    windows?: number;
  }>;
  totalBudget?: number;
  budgetBreakdown?: Array<{
    category: string;
    amount: number;
  }>;
}

/**
 * Generate PDF report for project
 */
export async function generateProjectPDF(data: ProjectExportData): Promise<Blob> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yPos = 20;

  // Header
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(41, 98, 255);
  pdf.text('HOUSPIRE', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 8;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text('Interior Design Project Report', pageWidth / 2, yPos, { align: 'center' });

  yPos += 15;

  // Project Details Box
  pdf.setDrawColor(41, 98, 255);
  pdf.setLineWidth(0.5);
  pdf.rect(15, yPos, pageWidth - 30, 30);

  yPos += 7;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 0, 0);
  pdf.text('Project Details', 20, yPos);

  yPos += 7;
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Project Name: ${data.projectName}`, 20, yPos);
  
  yPos += 6;
  pdf.text(`Client Name: ${data.clientName}`, 20, yPos);
  
  yPos += 6;
  pdf.text(`Location: ${data.city}`, 20, yPos);
  
  yPos += 6;
  pdf.text(`Date: ${data.date}`, 20, yPos);

  yPos += 15;

  // Rooms Overview
  if (data.rooms.length > 0) {
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Rooms Overview', 15, yPos);
    yPos += 10;

    // Create table data
    const tableData = data.rooms.map((room) => [
      room.roomName || 'Unnamed',
      room.roomType,
      `${room.area} sq ft`,
      room.style || 'Not selected',
      room.doors !== undefined ? room.doors : '-',
      room.windows !== undefined ? room.windows : '-',
      room.budget ? formatIndianCurrency(room.budget) : '-',
    ]);

    autoTable(pdf, {
      startY: yPos,
      head: [['Room Name', 'Type', 'Area', 'Style', 'Doors', 'Windows', 'Budget']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [41, 98, 255],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 25 },
        2: { cellWidth: 20 },
        3: { cellWidth: 25 },
        4: { cellWidth: 15 },
        5: { cellWidth: 15 },
        6: { cellWidth: 25 },
      },
    });

    yPos = (pdf as any).lastAutoTable.finalY + 15;
  }

  // Budget Summary
  if (data.totalBudget || data.budgetBreakdown) {
    // Check if we need a new page
    if (yPos > pageHeight - 60) {
      pdf.addPage();
      yPos = 20;
    }

    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Budget Summary', 15, yPos);
    yPos += 10;

    if (data.budgetBreakdown) {
      const budgetData = data.budgetBreakdown.map((item) => [
        item.category,
        formatIndianCurrency(item.amount),
      ]);

      autoTable(pdf, {
        startY: yPos,
        head: [['Category', 'Amount']],
        body: budgetData,
        theme: 'striped',
        headStyles: {
          fillColor: [41, 98, 255],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
        },
        styles: {
          fontSize: 10,
          cellPadding: 4,
        },
      });

      yPos = (pdf as any).lastAutoTable.finalY + 10;
    }

    if (data.totalBudget) {
      pdf.setFillColor(41, 98, 255);
      pdf.rect(15, yPos, pageWidth - 30, 15, 'F');
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(255, 255, 255);
      pdf.text('Total Project Budget:', 20, yPos + 10);
      pdf.text(formatIndianCurrency(data.totalBudget), pageWidth - 20, yPos + 10, {
        align: 'right',
      });
    }
  }

  // Footer
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(150, 150, 150);
  pdf.text(
    `Generated by HOUSPIRE on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return pdf.output('blob');
}

/**
 * Generate presentation-style PDF with images
 */
export async function generatePresentationPDF(data: ProjectExportData): Promise<Blob> {
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Cover Page
  pdf.setFillColor(41, 98, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  
  pdf.setFontSize(36);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(255, 255, 255);
  pdf.text(data.projectName, pageWidth / 2, pageHeight / 2 - 20, { align: 'center' });
  
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Client: ${data.clientName}`, pageWidth / 2, pageHeight / 2, { align: 'center' });
  
  pdf.setFontSize(14);
  pdf.text(`Location: ${data.city}`, pageWidth / 2, pageHeight / 2 + 15, { align: 'center' });

  // Room Pages
  for (const room of data.rooms) {
    pdf.addPage();
    
    // Room title
    pdf.setFillColor(41, 98, 255);
    pdf.rect(0, 0, pageWidth, 25, 'F');
    
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(255, 255, 255);
    pdf.text(room.roomName || 'Room', 15, 17);

    let yPos = 35;

    // Room details
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Type: ${room.roomType}`, 15, yPos);
    pdf.text(`Area: ${room.area} sq ft`, 80, yPos);
    if (room.style) pdf.text(`Style: ${room.style}`, 140, yPos);

    yPos += 10;

    // Images (if available)
    if (room.renderImage) {
      try {
        // In a real implementation, you'd need to load and convert the image
        // This is a placeholder
        pdf.text('[Render Image]', pageWidth / 2, pageHeight / 2, { align: 'center' });
      } catch (error) {
        console.error('Failed to add image:', error);
      }
    }

    // Room details footer
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    if (room.doors !== undefined) {
      pdf.text(`Doors: ${room.doors}`, 15, pageHeight - 15);
    }
    if (room.windows !== undefined) {
      pdf.text(`Windows: ${room.windows}`, 60, pageHeight - 15);
    }
    if (room.budget) {
      pdf.text(`Budget: ${formatIndianCurrency(room.budget)}`, 115, pageHeight - 15);
    }
  }

  // Thank you page
  pdf.addPage();
  pdf.setFillColor(41, 98, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  
  pdf.setFontSize(32);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(255, 255, 255);
  pdf.text('Thank You', pageWidth / 2, pageHeight / 2, { align: 'center' });
  
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'normal');
  pdf.text('HOUSPIRE - Transform Your Space', pageWidth / 2, pageHeight / 2 + 20, {
    align: 'center',
  });

  return pdf.output('blob');
}

/**
 * Download PDF
 */
export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate and download project report
 */
export async function downloadProjectReport(data: ProjectExportData) {
  const blob = await generateProjectPDF(data);
  const filename = `${data.projectName.replace(/\s+/g, '_')}_Report_${new Date()
    .toISOString()
    .split('T')[0]}.pdf`;
  downloadPDF(blob, filename);
}

/**
 * Generate and download presentation
 */
export async function downloadPresentation(data: ProjectExportData) {
  const blob = await generatePresentationPDF(data);
  const filename = `${data.projectName.replace(/\s+/g, '_')}_Presentation_${new Date()
    .toISOString()
    .split('T')[0]}.pdf`;
  downloadPDF(blob, filename);
}
