-- Emergency Synonyms Import: Critical furniture/lighting/decor synonyms
-- Using ON CONFLICT for the actual unique constraint (synonym, category)

-- Furniture Synonyms
INSERT INTO item_synonyms (synonym, canonical_name, category, confidence_score, source) VALUES
('leather sofa', '3-Seater Sofa', 'Furniture', 0.95, 'emergency_fix'),
('fabric sofa', '3-Seater Sofa', 'Furniture', 0.95, 'emergency_fix'),
('velvet sofa', '3-Seater Sofa', 'Furniture', 0.95, 'emergency_fix'),
('modern sofa', '3-Seater Sofa', 'Furniture', 0.95, 'emergency_fix'),
('contemporary sofa', '3-Seater Sofa', 'Furniture', 0.95, 'emergency_fix'),
('sectional sofa', 'L-Shaped Sofa', 'Furniture', 0.95, 'emergency_fix'),
('l-shaped sofa', 'L-Shaped Sofa', 'Furniture', 0.95, 'emergency_fix'),
('couch', '3-Seater Sofa', 'Furniture', 0.90, 'emergency_fix'),
('settee', '2-Seater Sofa', 'Furniture', 0.90, 'emergency_fix'),
('loveseat', '2-Seater Sofa', 'Furniture', 0.95, 'emergency_fix'),
('two-seater sofa', '2-Seater Sofa', 'Furniture', 0.95, 'emergency_fix'),
('accent chair', 'Single Seater Chair', 'Furniture', 0.95, 'emergency_fix'),
('lounge chair', 'Single Seater Chair', 'Furniture', 0.95, 'emergency_fix'),
('club chair', 'Single Seater Chair', 'Furniture', 0.95, 'emergency_fix'),
('wingback chair', 'Single Seater Chair', 'Furniture', 0.95, 'emergency_fix'),
('reading chair', 'Single Seater Chair', 'Furniture', 0.90, 'emergency_fix'),
('recliner', 'Recliner Chair', 'Furniture', 0.95, 'emergency_fix'),
('reclining chair', 'Recliner Chair', 'Furniture', 0.95, 'emergency_fix'),
('coffee table', 'Center Table', 'Furniture', 0.95, 'emergency_fix'),
('cocktail table', 'Center Table', 'Furniture', 0.90, 'emergency_fix'),
('centre table', 'Center Table', 'Furniture', 0.98, 'emergency_fix'),
('end table', 'Side Table', 'Furniture', 0.95, 'emergency_fix'),
('accent table', 'Side Table', 'Furniture', 0.90, 'emergency_fix'),
('lamp table', 'Side Table', 'Furniture', 0.90, 'emergency_fix'),
('entry table', 'Console Table', 'Furniture', 0.90, 'emergency_fix'),
('hallway table', 'Console Table', 'Furniture', 0.90, 'emergency_fix'),
('nesting tables', 'Nesting Tables', 'Furniture', 0.95, 'emergency_fix'),
('nested tables', 'Nesting Tables', 'Furniture', 0.95, 'emergency_fix'),
('book shelf', 'Book Rack', 'Furniture', 0.98, 'emergency_fix'),
('shelving unit', 'Open Shelf Unit', 'Furniture', 0.90, 'emergency_fix'),
('display shelf', 'Open Shelf Unit', 'Furniture', 0.90, 'emergency_fix'),
('tv unit', 'TV Stand', 'Furniture', 0.95, 'emergency_fix'),
('entertainment center', 'TV Stand', 'Furniture', 0.90, 'emergency_fix'),
('media console', 'TV Stand', 'Furniture', 0.90, 'emergency_fix'),
('tv cabinet', 'TV Stand', 'Furniture', 0.95, 'emergency_fix'),
('buffet', 'Sideboard', 'Furniture', 0.90, 'emergency_fix'),
('credenza', 'Sideboard', 'Furniture', 0.90, 'emergency_fix'),
('storage cabinet', 'Storage Cabinet', 'Furniture', 0.95, 'emergency_fix'),
('cabinet', 'Storage Cabinet', 'Furniture', 0.90, 'emergency_fix'),
('wooden coffee table', 'Center Table', 'Furniture', 0.95, 'emergency_fix'),
('glass coffee table', 'Glass Center Table', 'Furniture', 0.95, 'emergency_fix'),
('marble coffee table', 'Marble Center Table', 'Furniture', 0.95, 'emergency_fix'),
('wooden side table', 'Side Table', 'Furniture', 0.95, 'emergency_fix'),
('metal side table', 'Metal Side Table', 'Furniture', 0.95, 'emergency_fix'),
('round coffee table', 'Round Center Table', 'Furniture', 0.95, 'emergency_fix'),
('square coffee table', 'Center Table', 'Furniture', 0.90, 'emergency_fix'),
('leather armchair', 'Single Seater Chair', 'Furniture', 0.95, 'emergency_fix'),
('velvet armchair', 'Single Seater Chair', 'Furniture', 0.95, 'emergency_fix'),
('wooden bookshelf', 'Book Rack', 'Furniture', 0.95, 'emergency_fix'),
('metal bookshelf', 'Industrial Book Rack', 'Furniture', 0.90, 'emergency_fix')
ON CONFLICT (synonym, category) DO UPDATE SET 
  canonical_name = EXCLUDED.canonical_name,
  confidence_score = GREATEST(item_synonyms.confidence_score, EXCLUDED.confidence_score),
  source = 'emergency_fix',
  updated_at = now();

-- Lighting Synonyms
INSERT INTO item_synonyms (synonym, canonical_name, category, confidence_score, source) VALUES
('floor lamp', 'Standing Lamp', 'Lighting', 0.95, 'emergency_fix'),
('standing lamp', 'Standing Lamp', 'Lighting', 0.98, 'emergency_fix'),
('tripod lamp', 'Tripod Floor Lamp', 'Lighting', 0.95, 'emergency_fix'),
('tripod floor lamp', 'Tripod Floor Lamp', 'Lighting', 0.98, 'emergency_fix'),
('arc lamp', 'Arc Floor Lamp', 'Lighting', 0.95, 'emergency_fix'),
('arc floor lamp', 'Arc Floor Lamp', 'Lighting', 0.98, 'emergency_fix'),
('reading lamp', 'Reading Floor Lamp', 'Lighting', 0.90, 'emergency_fix'),
('table lamp', 'Table Lamp', 'Lighting', 0.98, 'emergency_fix'),
('desk lamp', 'Table Lamp', 'Lighting', 0.90, 'emergency_fix'),
('bedside lamp', 'Bedside Lamp', 'Lighting', 0.95, 'emergency_fix'),
('nightstand lamp', 'Bedside Lamp', 'Lighting', 0.90, 'emergency_fix'),
('pendant light', 'Pendant Light', 'Lighting', 0.98, 'emergency_fix'),
('pendant lamp', 'Pendant Light', 'Lighting', 0.95, 'emergency_fix'),
('hanging light', 'Pendant Light', 'Lighting', 0.95, 'emergency_fix'),
('chandelier', 'Chandelier', 'Lighting', 0.98, 'emergency_fix'),
('exposed bulb', 'Exposed Bulb Pendant', 'Lighting', 0.95, 'emergency_fix'),
('exposed bulb light', 'Exposed Bulb Pendant', 'Lighting', 0.95, 'emergency_fix'),
('industrial pendant', 'Industrial Pendant', 'Lighting', 0.95, 'emergency_fix'),
('ceiling light', 'Ceiling Light', 'Lighting', 0.95, 'emergency_fix'),
('flush mount', 'Flush Mount Light', 'Lighting', 0.95, 'emergency_fix'),
('modern floor lamp', 'Standing Lamp', 'Lighting', 0.95, 'emergency_fix'),
('brass floor lamp', 'Brass Floor Lamp', 'Lighting', 0.95, 'emergency_fix'),
('black floor lamp', 'Standing Lamp', 'Lighting', 0.90, 'emergency_fix'),
('white floor lamp', 'Standing Lamp', 'Lighting', 0.90, 'emergency_fix')
ON CONFLICT (synonym, category) DO UPDATE SET 
  canonical_name = EXCLUDED.canonical_name,
  confidence_score = GREATEST(item_synonyms.confidence_score, EXCLUDED.confidence_score),
  source = 'emergency_fix',
  updated_at = now();

-- Decor Synonyms
INSERT INTO item_synonyms (synonym, canonical_name, category, confidence_score, source) VALUES
('throw pillow', 'Cushion Cover', 'Decor', 0.95, 'emergency_fix'),
('decorative pillow', 'Cushion Cover', 'Decor', 0.95, 'emergency_fix'),
('accent pillow', 'Cushion Cover', 'Decor', 0.95, 'emergency_fix'),
('cushion', 'Cushion Cover', 'Decor', 0.90, 'emergency_fix'),
('scatter cushion', 'Cushion Cover', 'Decor', 0.95, 'emergency_fix'),
('area rug', 'Carpet', 'Decor', 0.95, 'emergency_fix'),
('rug', 'Carpet', 'Decor', 0.90, 'emergency_fix'),
('floor rug', 'Carpet', 'Decor', 0.95, 'emergency_fix'),
('throw blanket', 'Throw Blanket', 'Decor', 0.95, 'emergency_fix'),
('throw', 'Throw Blanket', 'Decor', 0.85, 'emergency_fix'),
('curtain', 'Curtains', 'Decor', 0.95, 'emergency_fix'),
('curtains', 'Curtains', 'Decor', 0.98, 'emergency_fix'),
('drapes', 'Curtains', 'Decor', 0.95, 'emergency_fix'),
('window curtain', 'Curtains', 'Decor', 0.95, 'emergency_fix'),
('sheer curtain', 'Sheer Curtains', 'Decor', 0.95, 'emergency_fix'),
('blinds', 'Window Blinds', 'Decor', 0.95, 'emergency_fix'),
('potted plant', 'Indoor Plant', 'Decor', 0.95, 'emergency_fix'),
('indoor plant', 'Indoor Plant', 'Decor', 0.98, 'emergency_fix'),
('houseplant', 'Indoor Plant', 'Decor', 0.95, 'emergency_fix'),
('plant', 'Indoor Plant', 'Decor', 0.85, 'emergency_fix'),
('planter', 'Plant Pot', 'Decor', 0.90, 'emergency_fix'),
('plant pot', 'Plant Pot', 'Decor', 0.95, 'emergency_fix'),
('artwork', 'Wall Art', 'Decor', 0.95, 'emergency_fix'),
('wall art', 'Wall Art', 'Decor', 0.98, 'emergency_fix'),
('painting', 'Wall Art', 'Decor', 0.90, 'emergency_fix'),
('framed art', 'Framed Print', 'Decor', 0.95, 'emergency_fix'),
('wall painting', 'Wall Art', 'Decor', 0.95, 'emergency_fix'),
('gallery wall', 'Gallery Wall Set', 'Decor', 0.90, 'emergency_fix'),
('geometric rug', 'Geometric Pattern Carpet', 'Decor', 0.90, 'emergency_fix'),
('persian rug', 'Persian Style Carpet', 'Decor', 0.95, 'emergency_fix'),
('jute rug', 'Jute Carpet', 'Decor', 0.95, 'emergency_fix')
ON CONFLICT (synonym, category) DO UPDATE SET 
  canonical_name = EXCLUDED.canonical_name,
  confidence_score = GREATEST(item_synonyms.confidence_score, EXCLUDED.confidence_score),
  source = 'emergency_fix',
  updated_at = now();